version: '3.8'

services:
  config-service:
    build: ./src/config-service
    container_name: config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-service:
    build: ./src/product-service
    container_name: product-service
    depends_on:
      - config-service
      - eureka-server
      - postgres-product
      - elasticsearch
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8082"

  stock-service:
    build: ./src/stock_service
    container_name: stock-service
    depends_on:
      - config-service
      - eureka-server
      - postgres-stock
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8084"

  auth-service:
    build: ./src/auth-service
    container_name: auth-service
    depends_on:
      - config-service
      - eureka-server
      - postgres-auth
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8081"

  eureka-server:
    build: ./src/eureka-server
    container_name: eureka-server
    depends_on:
      - config-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
    ports:
      - "5433:5432"

  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
    ports:
      - "5434:5432"

  postgres-stock:
    image: postgres:15
    container_name: postgres-stock
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
    ports:
      - "5435:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=pbIM1uTwqFm=Igi7btdc
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - config-service
      - product-service
      - stock-service
      - auth-service
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge