apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: enaya
data:
  init.sql: |
    CREATE DATABASE auth_db;
    
 
    CREATE USER auth_user WITH PASSWORD 'auth_password';
    GRANT ALL PRIVILEGES ON DATABASE auth_db TO auth_user;