apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: enaya
data:

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "auth_db"


  SERVER_PORT: "8081"
  SPRING_PROFILES_ACTIVE: "kubernetes"


  EUREKA_CLIENT_ENABLED: "false"


  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"