apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: enaya
type: Opaque
stringData:

  POSTGRES_USER: "auth_user"
  POSTGRES_PASSWORD: "auth_password"


  JWT_SECRET: "Ntu0p1j??AX,{oW5lLbkR6,):$ct,3.V|?^*dg^P6eo1ddYE>Iqpv#T9Sko:Ko}"
  JWT_ACCESS_TOKEN_EXPIRATION: "3600000"
  JWT_REFRESH_TOKEN_EXPIRATION: "86400000"


  GOOGLE_CLIENT_ID: "693221117307-ren5thjbfi1t7n9llu5bcobh29a2c78b.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  FACEBOOK_CLIENT_ID: "1222918276095862"
  FACEBOOK_CLIENT_SECRET: "809b23b99e263c3174a946397c7783e4"